### ISSUE TITLE
Package Control integration

### ISSUE THREAD

**Issue by Thom1729** [Thom1729/Sublime-JS-Custom#1]
This package [has been submitted](https://github.com/wbond/package_control_channel/pull/6810) to Package Control. When that PR is accepted, we can verify that the integration works as intended.

**Comment by Prestaul** [comment]
Any idea how long it might take to get the package to show up? The concept here is brilliant and I'm looking forward to giving it a test run.

**Comment by Thom1729** [comment]
No way to know. They're working to clear the backlog, so I'm optimistic. If you're anxious to give it a whirl, you can always install it manually by cloning the repo into your Packages directory as "JSCustom".

**Comment by Thom1729** [comment]
JS Custom is now available in Package Control!

Currently, only prerelease tags are available. You can install JS Custom via Package Control by adding `"install_rereleases": [ "JSCustom ]` to your Package Control user settings. I should release a production-ready 1.0.0 tag before the end of the week.

**Comment by Thom1729** [comment]
@Prestaul The 1.0.1 release is now available via Package Control.
