### ISSUE TITLE
Syntaxes and overrides not removed on uninstall

### ISSUE THREAD

**Issue by ViggoV** [Thom1729/Sublime-JS-Custom#102]
I uninstalled JSCustom to get rid of some hidden overrides to my preferred syntaxes (and preferences were not available from "Preferences > Package Settings" nor the Command Palette). However, the pesky syntaxes in question, and their overrides, were not removed. I had to manually delete them from the Packages folder. In other words my personal issue was resolved, but the Package Control > Remove Package command really should be able to remove everything.

**Comment by Thom1729** [comment]
It should be running the `clear_js_custom_user_data` command when the package is uninstalled. From the fact that this did not happen, and that you mention that the preferences were missing from the menu and the command palette, it sounds like something else was going wrong that was causing JS Custom not to work properly.

The only thing I can think of that should prevent the preferences from showing up in the menu is if the entire package were disabled. Is it possible that this happened?

Perhaps it should clear user data when the package is disabled and rebuild it when it is enabled. Unfortunately, there doesn't seem to be a Package Control event for this, so I'm not sure how I would implement it. Resolving #101 would probably render this moot.

**Comment by ViggoV** [comment]
No, the package was not disabled. I was using it for typescript.

**Comment by Thom1729** [comment]
Closing in favor of #101.
