### ISSUE TITLE
`xml.parsers.expat.ExpatError` after install

### ISSUE THREAD

**Issue by malthejorgensen** [Thom1729/Sublime-JS-Custom#103]
After installing JSCustom via Package Control I immediately get the following error (included package install as well for context):

```
reloading plugin JSCustom.plugin
JS Custom: New installation. Building all syntaxes.
reloading settings Packages/JSCustom/sublime/JS Custom.sublime-settings
generating syntax summary
generating meta info summary
JS Custom: Configuration changed. Rebuilding some syntaxes.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
  File "/Users/malthe/Library/Application Support/Sublime Text 3/Installed Packages/JSCustom.sublime-package/src/commands/build_syntaxes.py", line 51, in run
  File "/Users/malthe/Library/Application Support/Sublime Text 3/Packages/sublime_lib/st3/sublime_lib/syntax.py", line 96, in get_syntax_for_scope
    for syntax in reversed(list_syntaxes())
  File "/Users/malthe/Library/Application Support/Sublime Text 3/Packages/sublime_lib/st3/sublime_lib/syntax.py", line 83, in list_syntaxes
    for path in syntax_definition_paths
  File "/Users/malthe/Library/Application Support/Sublime Text 3/Packages/sublime_lib/st3/sublime_lib/syntax.py", line 86, in <listcomp>
    and path.with_suffix('.sublime-syntax') in syntax_definition_paths
  File "/Users/malthe/Library/Application Support/Sublime Text 3/Packages/sublime_lib/st3/sublime_lib/syntax.py", line 55, in get_syntax_metadata
    **SYNTAX_TYPES[path.suffix](path)
  File "/Users/malthe/Library/Application Support/Sublime Text 3/Packages/sublime_lib/st3/sublime_lib/syntax.py", line 36, in get_hidden_tmlanguage_metadata
    tree = plistlib.readPlistFromBytes(path.read_bytes())
  File "./python3.3/plistlib.py", line 104, in readPlistFromBytes
  File "./python3.3/plistlib.py", line 76, in readPlist
  File "./python3.3/plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 7, column 0
```

Also, when I open up the JSCustom preferences and try to save I get the message:

```
Unable to save ~/Library/Application Support/Sublime Text 3/Packages/JSCustom/sublime/JS Custom.sublime-settings
Error: No such file or directory
```

`~` is `/Users/malthe`. 
`~/Library/Application Support/Sublime Text 3/Packages/JSCustom/` doesn't exist.
`~/Library/Application Support/Sublime Text 3/Packages/User/JS Custom/Syntaxes/` exists but is empty.

**Comment by malthejorgensen** [comment]
The first part was caused by the package `AutoDocstring`, specifically `Packages/AutoDocstring/ADMagicPython.hidden-tmLanguage`. Removing the `AutoDocstring`-package fixed the issue.

**Comment by malthejorgensen** [comment]
Second part with the "unsaveable" settings seems intended. Closing issue.

**Comment by Thom1729** [comment]
Were you editing the default settings (on the left) rather than the user settings (on the right)? It sounds like you've worked it out either way.

**Comment by malthejorgensen** [comment]
Yes, exactly that. I was desperately trying to get it to work, but didn't know it was all caused by the first error with `AutoDocstring` at the time 😅

**Comment by malthejorgensen** [comment]
Not sure if this is deserving of a new issue, but I'm having some issues with syntax highlighting, or we're all just waiting for Sublime Text 4 to land. Seems to be caused by the multiline generic args to `reduxForm`:

<img width="727" alt="Screen Shot 2021-03-27 at 00 42 42" src="https://user-images.githubusercontent.com/615776/112702908-5b6be100-8e95-11eb-9741-72da418b6b79.png">

**Comment by Thom1729** [comment]
Is that Flow or TypeScript?

TypeScript support in 2.4 is experimental and not super great. Version 3.0 offers much better TypeScript support (developed in concert with the new core TypeScript syntax) but relies on ST4 features. If you're on the ST4 beta, you can get the latest JS Custom 3.0 alpha by adding `"install_prereleases": ["JSCustom"]` to your Package Control config.

If that's Flow, then honestly the Flow extension is going to need an almost complete rewrite for 3.0, which I haven't begun. The 3.0 TypeScript extension might actually provide better highlighting for Flow at this point.

The problem in this case is that the 2.4 extensions don't know about generic type parameters to functions. This is very difficult to do without the new ST4 syntax features and I doubt that I'll ever make them work for a ST3-compatible release.

**Comment by malthejorgensen** [comment]
This is TypeScript – sounds good – I was planning to upgrade to the beta of Sublime Text 4 anyways, so will do that in the coming days :)
