### ISSUE TITLE
Multi-line comment breaks highlighting

### ISSUE THREAD

**Issue by jeremytm** [Thom1729/Sublime-JS-Custom#106]
Seems to be an error with general JS multi-line comments. This breaks DocBlockr code for example.

Using ST3, with JSCustom React syntax highlighting. This issue just appeared for me today, I assume after the latest update was installed.

![image](https://user-images.githubusercontent.com/6539834/115481211-3a35bf00-a2a0-11eb-8b24-691b6c540786.png)

Copy-pastable code
```
// Normal highlighting
let x = 1;

/***/ // Should be normal highlighting
let y = 1;
```

**Comment by Thom1729** [comment]
I bet this is the same issue as https://github.com/babel/babel-sublime/issues/403. I solved it over there with an ad-hoc patch.

Whatever the problem was, it seems to be fixed on the latest dev build for ST4. I'm in the process of releasing a stable ST4 version; once that's done I might see about patching the ST3 branch.

**Comment by Thom1729** [comment]
Actually, can you check what version you have installed? I just noticed that you said this was a new problem, but there shouldn't be any ST3-compatible updates — not in months.

**Comment by jeremytm** [comment]
Sublime Text 3.2.2 Build 3211

I'm not actually certain it was an update. I re-launched Sublime Text for the first time in a while today — but certainly not months since I last restarted my macbook.

I have JSCustom 3.0.1 installed
![image](https://user-images.githubusercontent.com/6539834/115492292-a5d65700-a2b5-11eb-8931-a3a1a1b48472.png)

**Comment by jeremytm** [comment]
The issue is resolved now (after rebuilding syntaxes). Thanks!
