### ISSUE TITLE
Latest build - Error loading syntax file "Packages/User/JS Custom/Syntaxes/TypeScript (JSX).sublime-syntax"

### ISSUE THREAD

**Issue by Shelagh-Lewins** [Thom1729/Sublime-JS-Custom#107]
JS Custom just updated to v3.0.0 in Sublime Text 3 and is now broken. The release notes say that this release is designed for Sublime Text 4 but is there some way to still use JS Custom in Sublime Text 3?

On loading Sublime Text 3 I see this error:

`error: Error loading syntax file "Packages/User/JS Custom/Syntaxes/TypeScript (JSX).sublime-syntax": Unable to read Packages/User/JS Custom/Syntaxes/TypeScript (JSX).sublime-syntax`

**Comment by Thom1729** [comment]
Version 3 is supposed to be exclusive to Sublime Text 4. Obviously, things went wrong. As an immediate fix, I've released v3.0.2, which should be identical to v2.4.2.

**Comment by bcomnes** [comment]
Getting the same error on Sublime text 4102 w/ js custom on 3.0.1

**Comment by Thom1729** [comment]
v3.0.2 should fix it. I only released it an hour ago; it may still be percolating through Package Control.

**Comment by bcomnes** [comment]
This is the best JS Syntax highlighting package on the entire planet btw. Beats everything over on VSCode that I've managed to try.  Thank you!

**Comment by Thom1729** [comment]
Thanks! I take it that means it's working now?

**Comment by bcomnes** [comment]
No still stuck on 3.0.1.

**Comment by bcomnes** [comment]
Ok working again on 3.0.2 in sublime text 3.  

Do you know if JSCustom 3.0.2 would work in Sublime text 4?

**Comment by bcomnes** [comment]
I'm still trying to verify this, but it looks like I'm getting syntax highlighting errors on JSX files now, even with the JSX option turned on.

**Comment by Shelagh-Lewins** [comment]
With version 3.0.2 in Sublime Text 3, the errors are gone and it is usable again. Thank you!

I am still seeing some highlighting errors in JSX, but this may be a different issue?

Some closing brackets and braces are highlighted in hot pink, and some closing tags such as </div> are coloured as text. Should I raise this as a new issue?

**Comment by bcomnes** [comment]
I opened a new issue for the JSX highlighting issues in 3.0.2 here: https://github.com/Thom1729/Sublime-JS-Custom/issues/109

**Comment by Thom1729** [comment]
> Do you know if JSCustom 3.0.2 would work in Sublime text 4?

Yes. All versions work in ST4. The new ST4-exclusive version (which got messed up here) provides better highlighting using ST4 features.
