### ISSUE TITLE
JSX Highlighting broken on 2.4.2/3.0.2

### ISSUE THREAD

**Issue by bcomnes** [Thom1729/Sublime-JS-Custom#109]
JSX highlighting working on 2.4.1:

<img width="683" alt="Screen Shot 2021-04-21 at 10 08 39 AM" src="https://user-images.githubusercontent.com/166301/115586463-d99b8780-a289-11eb-8c32-c2e5117b9316.png">

JSX Highlighting on 2.4.2/3.0.2

<img width="684" alt="Screen Shot 2021-04-21 at 10 10 11 AM" src="https://user-images.githubusercontent.com/166301/115586499-e324ef80-a289-11eb-81ea-f6c4bc6e9b3b.png">

Running sublime text 3211

Running this custom config:

```json
{
  "configurations": {
        "Javascript Custom": {
          "jsx": true,
          "eslint_directives": true,
          "custom_templates": {
                "tags": {
                    "css": "scope:source.css",
                    "csjs": "scope:source.css",
                    "(s) => ":  "scope:source.css",
                    "html": "scope:text.html.basic",
                    "this.html": "scope:text.html.basic",
                },
                "comments": {
                  "GraphQL": "scope:source.graphql",
                  "gql": "scope:source.graphql"
                }
            }
        }
    }
}
```

**Comment by bcomnes** [comment]
Temporary work around:

Clone this repo into `Sublime Text 3/Packages` named as JSCustom and then check out tag `v2.4.1`.  Restart Sublime text a few times when it asks you to.

**Comment by Shelagh-Lewins** [comment]
I'm seeing several issues with highlighting JSX files in JS Custom 3.0.2, Sublime Text 3 on Linux Mint.

![JS Custom issues](https://user-images.githubusercontent.com/15693742/115587716-e3db7700-a2c5-11eb-8ec1-dcceddd84c34.png)


1. Closing curly bracket in pink
2. MyView class name not highlighted
3. Closing </div> tag and everything after it marked as string

I have no custom configuration and am running the Default theme.

**Comment by Thom1729** [comment]
I've just released v3.0.3, which should be exactly identical to v2.4.1. This should resolve any remaining issues with the v3-on-ST3 comedy of errors.

**Comment by bcomnes** [comment]
Sweet thank you @Thom1729 ! Sublime text packaging is rough.

**Comment by bcomnes** [comment]
Closing

**Comment by Thom1729** [comment]
@bcomnes Just to be sure, can you confirm that the problem is actually fixed?

**Comment by bcomnes** [comment]
Its working on a local checkout.  Tag is there, so its just a matter of waiting for PC to catch up.

**Comment by bcomnes** [comment]
v3.0.1 is still having syntax building issues (on local checkout) on sublime text 4.

**Comment by zpetukhov** [comment]
Hi to all.
v3.0.3 fixed the issue for me.
But today my ST3 has upgraded to v3.0.4.
And JSX syntax is broken again.
(Taking this opportunity: huge thanks for the package).

**Comment by bcomnes** [comment]
Latest version is working on Sublime text 4 as far as I can tell.

**Comment by zpetukhov** [comment]
Below is screenshots of 3.0.4, 3.0.3 and 3.0.2 in ST3.
![3 0 4](https://user-images.githubusercontent.com/699175/117377226-73df0a80-aedb-11eb-841d-4fe578a23060.png)
![3 0 3](https://user-images.githubusercontent.com/699175/117377229-7477a100-aedb-11eb-8b96-6b1a5cfd7ba3.png)
![3 0 2](https://user-images.githubusercontent.com/699175/117377231-75a8ce00-aedb-11eb-9229-31cbffa84f77.png)

**Comment by Thom1729** [comment]
So it turns out I'm really bad at naming tags. I need to write a script for that rather than doing it manually.

v3.0.5 should fix everything. Please let me know if it does not.
