### ISSUE TITLE
Syntax and commenting issues with TS Generics

### ISSUE THREAD

**Issue by ivanddm** [Thom1729/Sublime-JS-Custom#126]
I just checked setting JSCustoms in tsx files. I'm getting the following with the default syntaxes that are installed when you install JSCustom:

- JS Custom Default: working for syntax of regular JS-JSX-TS-TSX, not for commenting the JSX part (adds // intead of {/* */}).
- JS Custom React: working for JS-JSX-TS-TSX but uncommenting does not remove the curly braces.
- JS Custom Typescript: working for syntax of regular JS-JSXTS-TSX, not for commenting the JSX part (adds // intead of {/* */})
- JS Custom Typescript (JSX): not working at all, same issue as illustrated in [Packages #2529](https://github.com/sublimehq/Packages/issues/2529#issuecomment-891241351).

The built-in JS-JSX-TS-TSX syntax that comes with ST4, based on initial trials, works as expected,  that is, the new built-in syntaxes do proper commenting and uncommenting of JSX (they also remove the curly braces when uncommenting) as well as proper syntax even with TS generics such as `React.FC<{...}>`.

**Comment by ivanddm** [comment]
**Update**: Actually, although I had reinstalled JSCustoms, the old syntaxes were still in my package folder 🤦🏻‍♂️. After rebuilding JS Custom syntaxes, I can say that they work as expected just like the ST4 built-in ones.

Thanks again!

**Comment by ivanddm** [comment]
However, I would like to ask you, should I prefer ST4 built-in syntaxes over JSCustom or vice-versa?

**Comment by Thom1729** [comment]
JS Custom is derived directly from the core syntaxes, and in such a way that I can keep it in sync with the core packages as they update. The only difference in behavior should be the configuration options you use. Therefore, the only reason to use JS Custom is if you use those options.
