### ISSUE TITLE
Unable to find JSCustom on package control

### ISSUE THREAD

**Issue by kaiser101** [Thom1729/Sublime-JS-Custom#128]
Its the old error again. JSCustom missing.
[](url
![jscustom_missing](https://user-images.githubusercontent.com/1123273/139534125-75a3fe21-ed98-4d42-977f-d3ae21d1d687.png)
)

**Comment by Thom1729** [comment]
Ugh, not again. I've deleted some tags, which might do the trick.

**Comment by kaiser101** [comment]
Thanks for the quick update. Its still showing missing, so will check tomorrow.

**Comment by Thom1729** [comment]
If merely deleting the extra tags works, then it might take an hour or so.

**Comment by Thom1729** [comment]
Relevant: https://github.com/wbond/packagecontrol.io/issues/143

**Comment by Thom1729** [comment]
It's back up. Looks like at first, I only deleted releases, not the actual tags.

**Comment by kaiser101** [comment]
Thanks that worked. You can close it now.
