### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by laurent-kir** [Thom1729/Sublime-JS-Custom#135]
Hey @Thom1729! Whenever I try to call the `build_js_custom_syntaxes` command, the process fails. A directory "**JS Custom/Syntaxes**" is created in the folder "**User**", but it is empty.
Here's what the console outputs at the same time:

> Traceback (most recent call last):
>   File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 1456, in run_
>     return self.run(**args)
>   File "C:\Users\USERNAME\AppData\Roaming\Sublime Text\Installed Packages\JSCustom.sublime-package\src/commands/build_syntaxes.py", line 62, in run
>   File "C:\Users\USERNAME\AppData\Roaming\SUBLIM~1\Packages\SUBLIM~1\st3\sublime_lib\syntax.py", line 100, in get_syntax_for_scope
>     raise ValueError("Cannot find syntax for scope {!r}.".формат(scope)) from None
> ValueError: Cannot find syntax for scope 'source.js'.

**P.S.** What am I doing wrong?

**Comment by Thom1729** [comment]
What version of Sublime are you running?

I notice that the line `raise ValueError("Cannot find syntax for scope {!r}.".формат(scope)) from None` has Greek letters in it, which is definitely not normal. Do you know what's going on with that?

**Comment by laurent-kir** [comment]
ST: 4.1.2.6
OS: Windows 10 Pro x64

> I notice that the line... has Greek letters

Are you talking about the substring `формат`? It's Cyrillic. And I do not know where these symbols come from here; I remember for sure that the console did not output anything like this. Probably, this is some kind of oddity with formatting on github. Fuck knows.

PS It's strange, but today the problem has disappeared. All syntax files were generated successfully.

**Comment by Thom1729** [comment]
I'll chalk it down to cosmic rays for the time being. But please reopen if the problem occurs again.
