### ISSUE TITLE
Highlight errors when destructuring inside an object

### ISSUE THREAD

**Issue by ellipticaldoor** [Thom1729/Sublime-JS-Custom#19]
![image](https://user-images.githubusercontent.com/3449006/36933362-6cfbbe88-1ecf-11e8-9b39-b0065e46fa1b.png)

You can see in the image that the highlight stops working in line 9.

If you remove all the destructuring the highlight starts to work fine.

A copy of the code:
``` javascript
import { mapActions, mapGetters, mapState } from 'vuex'

export default {
	name: 'App',

	computed: {
		...mapState('auth', ['payload']),
		...mapGetters('users', { getUserInStore: 'get' }),
		...mapGetters('vaults', { getVaultInStore: 'get' }),
		...mapGetters('resources', { getResourcesInStore: 'get' }),
		...mapGetters('dwellers', { findDwellersInStore: 'find' }),
		...mapGetters('crafts', { findCraftsInStore: 'find' }),
		...mapGetters('scores', { getScoresInStore: 'get' }),
	},

	methods: {
		...mapActions('users', { getUser: 'get' }),
		...mapActions('vaults', { getVault: 'get' }),
		...mapActions('dwellers', { findDwellers: 'find' }),
		...mapActions('crafts', { findCrafts: 'find' }),
		...mapActions('resources', { getResources: 'get' }),
		...mapActions('scores', { getScores: 'get' }),
	},
}

```

**Comment by Thom1729** [comment]
This is an underlying bug with the core JavaScript syntax (which is probably my fault anyway). I've submitted a PR for the core syntax, and I've already applied the patch to JS Custom.

If the PR is not accepted in the next Sublime build, I may have to re-patch JS Custom, but I'm confident that the temporary discrepancy will be resolved soon.

**Comment by ellipticaldoor** [comment]
Looks like in sublime text dev works just fine

**Comment by Thom1729** [comment]
It looks like the bug was [introduced by me](https://github.com/sublimehq/Packages/commit/2252a825) on December 4, 2017.

**Comment by Thom1729** [comment]
Also, v1.10.0 is now available, which should fix this issue.

**Comment by ellipticaldoor** [comment]
Thank you!

**Comment by Thom1729** [comment]
Thank you for reporting this issue and the others!
