### ISSUE TITLE
Setting JS Custom as the default syntax to open .js/.jsx in

### ISSUE THREAD

**Issue by audiolion** [Thom1729/Sublime-JS-Custom#25]
![image](https://user-images.githubusercontent.com/2430381/37727987-7f44c80c-2d0f-11e8-9b55-372331413b35.png)

It isn't available as an option. im not going to cmd+shift+p into command palette and set this syntax for every file I open

**Comment by Thom1729** [comment]
Your JS Custom syntaxes will appear in that menu under User.* (This needs to be added to the documentation.) Does this solve your problem?

\* This is because the compiled syntax definition files are placed under User/JS Custom/Syntaxes. It would be nice to have them under "JS Custom" instead, but unfortunately this is just how Sublime generates that menu.

**Comment by audiolion** [comment]
Ahhh, ok. yeah

![image](https://user-images.githubusercontent.com/2430381/37728911-e6d56a60-2d11-11e8-92c4-ea1c94b0d00b.png)

Definitely add that to the docs!

**Comment by Thom1729** [comment]
I've added an FAQ section starring this issue. Would you mind giving it a look?

**Comment by audiolion** [comment]
Yeah looks good, I would almost say this should be part of the `installation` section though, and a picture says a thousand words, no harm in including one I wouldn't think but its your call

**Comment by rdela** [comment]
Maybe even explaining the `Open all with current extension as…` step in `Installation`.

Initially I thought I needed to customize my syntaxes by choosing Preferences → Package Settings → JS Custom → Settings as described in Usage, but all I needed was to open a `.js` file and `Open all with current extension as…` User → JS Custom - React.

I am a former (as of today 🎉) `babel-sublime` user and I just wanted JSX support so `Open all with current extension as…` was all I needed.

Very happy about https://github.com/Thom1729/Sublime-JS-Custom#jsx_close_tag-boolean

> `jsx_close_tag: boolean`
> If true, when you run the close_tag command in a JavaScript file, this package's jsx_close_tag command will be invoked instead.

That alone made JS Custom an instant improvement for me 🙇 🙏 

Very glad to have found it via https://twitter.com/wbond/status/993486942393249792 finally got around to swapping it in today and I concur, it is a “solid upgrade  over Babel.”

With minor readme changes like these it could live up to the “drop-in replacement for [babel-sublime](https://github.com/babel/babel-sublime)” promise as well.

**Comment by rdela** [comment]
Happy to work on a PR for this if you are game @Thom1729
