### ISSUE TITLE
Syntax is missing function-call section.

### ISSUE THREAD

**Issue by deathaxe** [Thom1729/Sublime-JS-Custom#26]
I am using `JS Custom` to play around with React JSX files. 

I found `function-call` section not being part of the generated React.sublime-syntax and Default.sublime-syntax files even though they are used within those files. Furthermore other languages seem to reference them or at least cause ST to throw the following errors while embedding them.

```
no such context scope:source.js#function-call at line 1871 column 20 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.js#function-call at line 1893 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
```

**Comment by Thom1729** [comment]
The `function-call` scope has been refactored out of the core syntax, so this should no longer be an issue. (Please reopen this if it recurs, of course.)
