### ISSUE TITLE
Flow: Generic type parameters not supported on arrow functions

### ISSUE THREAD

**Issue by clark-pan** [Thom1729/Sublime-JS-Custom#28]
I'm using version v1.1.0-alpha.2

Generic types for arrow functions don't seem to be working.

<img width="336" alt="screen shot 2018-04-11 at 10 24 37 am" src="https://user-images.githubusercontent.com/1161431/38593301-4bb39198-3d73-11e8-9bb1-fb0df51b3c80.png">

**Comment by Thom1729** [comment]
Thanks for the find.

I'll take a more detailed look at this, but this may be a case where we'll have to use an unreliable heuristic. It looks like you're using JSX as well, and `<T>` looks like a JSX tag. It is absolutely impossible for a sublime syntax to tell the difference in the general case. In fact, I'm not sure how this isn't a genuine grammatical ambiguity.

See [this TypeScript issue](https://github.com/Microsoft/TypeScript/issues/15713), which is closed as a “Design Limitation”.

In the mean time, I'd suggest using `function<>` as a workaround.

**Comment by clark-pan** [comment]
Thanks for looking into it. I'm not 100% familiar with how sublime syntax stuff works, but is there no way to capture the opening tag of jsx and only consider it jsx if theres a closing matching tag?

So a <T> just on its own is considered flow type, but <T></T> is actually what makes it JSX (or <T /> as well i guess)

**Comment by Thom1729** [comment]
@neutraali I've just fixed this in 1.0.19. The problem was that `typeof` expected an expression, and so it parsed the `>` as a greater-than operator. I have modified the Flow extension so that typeof will expect a LeftExpression. Please let me know if that problem recurs.

**Comment by neutraali** [comment]
Thanks @Thom1729 :+1: - Will do just as soon as you upload that to [Package Control](https://packagecontrol.io/packages/JSCustom) :smile_cat:
