### ISSUE TITLE
Recommended color schemes?

### ISSUE THREAD

**Issue by qrohlf** [Thom1729/Sublime-JS-Custom#35]
Unfortunately, even with this language syntax definition, the default Sublime color schemes leave a lot to be desired. 

The old babel-sublime package provided some bundled textmate themes that were set up to handle the babel syntax definitions, but I'm not aware of anything like that for this package. Could you perhaps share the syntax theme that you're currently using?

**Comment by Thom1729** [comment]
I use the default Mariana, but with the colors brightened and with extra highlighting applied to object keys:

```json
{
    "variables":
    {
        "blue5": "hsl(180, 60%, 55%)",
        "red": "hsl(357, 88%, 65%)",
        "orange": "hsl(32, 95%, 66%)",
        "green": "hsl(114, 35%, 68%)",
        "blue": "hsl(210, 60%, 62%)",
        "pink": "hsl(300, 45%, 68%)",
    },
    "rules": [
        {
            "name": "JavaScript unquoted object literal key",
            "scope": "meta.object-literal.key, meta.object-literal.key string - punctuation, meta.mapping.key string - punctuation",
            "foreground": "var(blue5)"
        },
    ]
}
```

**Comment by kylebebak** [comment]
@qrohlf 

To do what he's suggesting, create a **sublime-color-scheme** file in your **User** directory. I use the Solarized (Light) color scheme, so I created the file **User/Solarized (Light).sublime-color-scheme** to override some of this scheme's rules. Here's what this file might look like:

```json
{
  "rules":
  [
    {
      "name": "Markup Error",
      "scope": "markup.error",
      "foreground": "#DD0000"
    },
    {
      "name": "Markup Warning",
      "scope": "markup.warning",
      "foreground": "#0000DD"
    },
    {
      "name": "JavaScript unquoted object literal key",
      "scope": "meta.object-literal.key, meta.object-literal.key string - punctuation, meta.mapping.key string - punctuation",
      "foreground": "#C9146F"
    },
  ]
}
```
