### ISSUE TITLE
Rebuilding is broken

### ISSUE THREAD

**Issue by szw** [Thom1729/Sublime-JS-Custom#36]
Hi!

After the last change rebuilding seems to be broken. I've tried to rebuild syntaxes after installing the plugin either from Github or from Package Control. After restarting and having all dependencies installed, on command `Rebuild Syntaxes` it creates the `User/JS Custom/Syntaxes` directory and stops there (directory is empty). No syntax files are generated and no info is shown either.

Here are my plugin settings, which worked well in the previous version:

```JSON
{
   "defaults": {
        "es_decorators": false,
        "eslint_directives": true
    },
     "configurations": {
        "ES8": {
          "file_extensions": [ "js", "mjs" ]
        },
        "JSX": {
            "file_extensions": [ "jsx" ],
            "flow_types": false,
            "jsx": true
        }
    }
}
```

**Comment by Thom1729** [comment]
I've just released 1.0.17, which corrects a critical bug in 1.0.16. Please let me know if that fixes the problem.

**Comment by szw** [comment]
Great! Now it works! Thanks!

**Comment by string-areeb** [comment]
Hello, I'm facing the same issue. There is no output in console or the directory on rebuilding
