### ISSUE TITLE
How to embed text.html.basic into javascript template tags?

### ISSUE THREAD

**Issue by evandrocoan** [Thom1729/Sublime-JS-Custom#39]
I am using this configuration:
```json
{
    "defaults": {
        "comma_operator": false,
        "custom_tagged_literals": false,
        "es_decorators": true,
        "flow_types": false,
        "jsx": false,
    },

    "configurations": {
        "Default": {},
        "React": {
            "custom_template_tags": {
                "style": "scope:text.html.basic"
            },
        }
    },

    "auto_build": true,
    "jsx_close_tag": true
}
```

But the file still not highlighting html:

![image](https://user-images.githubusercontent.com/5332158/42544947-22c5578a-848b-11e8-94e4-7ae3de5ba935.png)

**Comment by evandrocoan** [comment]
Thanks! I missed that `style` on the example. However, I have no tag for it on this case. Could I set a regex `innerHTML\s*=\s*` as the prefix? Then, it would always work for explicit `innerHTML` assignments.

I tried with this setting:
```json
                "innerHTML\\s*=\\s*": "scope:text.html.basic"
```
Which generated the following syntax:
```yaml
    - match: (innerHTML\s*=\s*)\s*(`)
```

But it still not working:

![image](https://user-images.githubusercontent.com/5332158/42546245-f36d2956-8492-11e8-8ced-c6d95573f2d9.png)

**Comment by Thom1729** [comment]
Unfortunately, that will not work. The `custom_template_tag` feature is designed specifically to work with ECMAScript tagged template literals. However, you can create your own custom template tag:

```js
const html = String.raw;

html`
<!-- Navbar -->
`;
```

**Comment by evandrocoan** [comment]
Thanks for the working alternative. But I do not like this approach on the `innerHTML =` context, because the HTML scope could already be inferred from `innerHTML =`

I see that currently it does not work because when I do `innerHTML\s*=\s*`, it cannot match `innerHTML =` because Sublime Text syntax engine has already consumed these characters `innerHTML =`

A solution would be to put the expression before the Sublime Text has the chance consume it, however, but I think it is impossible do so generally because you have to manually apply the correct scopes for `innerHTML =`

I think it could be possible to manually implement the syntax only for this case or some similar, by matching `innerHTML =` before other Sublime Text syntax rules, apply the their scope and then push the HTML syntax scope.

**Comment by string-areeb** [comment]
I think a better solution will be to allow users to do things like this VS Code plugin - https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates

**Comment by Thom1729** [comment]
That could work. Thanks for the reference. Could you open a new issue for the suggested enhancement?

**Comment by string-areeb** [comment]
Thanks. Created as #49
