### ISSUE TITLE
Regexps that include forward slash are broken (edit: not actually broken)

### ISSUE THREAD

**Issue by Mitranim** [Thom1729/Sublime-JS-Custom#40]
Consider the following two regexes:

```js
// valid regex
/[/]/

// valid regex
/\//
```

Both regexes have an escaped forward slash. Right now, JS Custom fails to detect the escaping, and prematurely ends regex parsing. The remainder of the regex confuses the parser, and the following code is scoped incorrectly.

**Comment by Thom1729** [comment]
I can't reproduce. What settings are you using? Is it possible that another package is providing `source.regexp.js` highlighting?

In the example, the expression doesn't end after the first regexp, so the next slash is (correctly) interpreted as a division operator, not the beginning of a regexp. I don't know if this is relevant to the issue.

**Comment by Mitranim** [comment]
While writing the response, I found that enabling the default `JavaScript` package solved the problem. It might have other adverse effects; this remains to be seen. When installing an alternative language definition, disabling the built-in is usually a no-brainer. Do you keep it enabled? Does JS Custom depend on the default package? If so, this should probably be explained in the readme.

**Comment by Thom1729** [comment]
I do keep the default package enabled. It actually didn't occur to be to disable it, but now that you mention it I can see that it would make sense to do. For now, I'll add a note to the readme.

What's the issue with the indentation rules? I wasn't aware of any adverse interactions.

**Comment by Mitranim** [comment]
First issue that comes to mind: multiline parentheses. Consider this code:

```js
someFunc(
  someArg,
)
```

When typing `someFunc()` and pressing Enter, I want this:

```js
someFunc(
  |  <-- cursor
)
```

With the built-in indentation rules, the two examples look like this:

```js
someFunc(
  someArg,
  )

someFunc(
  |  <-- cursor
  )
```

And any following code will be indented even further. This is, of course, ridiculous. I hope nobody _actually_ likes this behavior, and we could agree to fix this in the built-in packages.

My custom JS indentation rules look like this: https://gist.github.com/Mitranim/2d534a720826e896ac2a9ca1ca1627de. They actually produce the desired behavior, but _only_ when the default package is disabled.

**Comment by Thom1729** [comment]
That does sound like a good change to submit to the core Packages repo.

**Comment by Mitranim** [comment]
For completeness, let me mention other issues in the default package and why one might prefer to disable it:

* imperfect indentation rules
* annoying snippets
* annoying comment rules (no spaces for `/*` and `*/`)
* suppresses autocompletion after `function` and some other keywords, really annoying

I wonder how other folks feel about this.
