### ISSUE TITLE
Rebuilding of syntaxes does not work when cloned from Github

### ISSUE THREAD

**Issue by szw** [Thom1729/Sublime-JS-Custom#41]
Hi!

It looks like rebuilding doesn't longer work when JSCustom is installed directly from Github. Steps to reproduce:

```Console
cd ~/Library/Application\ Support\Sublime\ Text \3/Packages
git clone https://github.com/Thom1729/Sublime-JS-Custom.git JSCustom
```

After cloning, restarting, installing dependencies, when finally `Rebuild Syntaxes` command becomes available, it shows empty console window and stops there. 

The version from Package Control works fine.

Best regards,

szw

**Comment by Thom1729** [comment]
Do you generally use the manual installation option? Would anyone be upset if I removed it from the documentation?

If the answer is yes, then of course I would like to preserve it, and fix it as needed. I'll look into the error this weekend.

**Comment by szw** [comment]
Thanks! Yes, I use it as a main one, because I keep my own fork with legacy JS keywords highlighting support removed. I work mainly in Node JS, and random DOM stuff highlighted I find really annoying. It would be great to either keep manual installation or have an option to disable legacy support... :)

**Comment by Thom1729** [comment]
Factoring out environment-specific variables is a work in progress (#30). For the next step, I'm waiting on [a Core PR](https://github.com/sublimehq/Packages/pull/1641).

**Comment by Thom1729** [comment]
@szw Does this error occur with v2.0.0?
