### ISSUE TITLE
"Advanced usage" from babel-sublime

### ISSUE THREAD

**Issue by francislavoie** [Thom1729/Sublime-JS-Custom#42]
So in https://github.com/babel/babel-sublime/blob/master/README.md, it mentions in "Advanced usage" that disabling the default `JavaScript` package will let the babel version take over as the default.

Is the equivalent possible with this package? This is relevant because the `Vue Component` package recommends doing that. See here: https://github.com/vuejs/vue-syntax-highlight#enabling-jsx-highlighting

If this is a drop-in replacement for `babel-sublime`, I'd expect it to be able to do the same and act as the default package, but it didn't seem to work. Maybe I'm just doing it wrong? :man_shrugging: 

Thanks

**Comment by kylebebak** [comment]
@francislavoie 

Hey there. I think what you want to do is set the default syntax to **JS Custom - Default** for all files that have a given extension. To see how you would do this, just have a look at the screenshot below. Does that help?

<img width="1164" alt="screen shot 2018-08-14 at 7 31 52 pm" src="https://user-images.githubusercontent.com/1524088/44125570-04d880c4-9ff9-11e8-9afd-52e656f2a9bc.png">

**Comment by francislavoie** [comment]
No that's not right. I need to use the Vue Component syntax highlighting, but this JS package embedded inside it. Vue component files can have multiple languages inside of them (html, css, multiple variants of js, jsx, etc) and as linked, the Vue Component package recommends specific steps to take for good compatibility with babel-sublime so that there's better JS support. But this package is meant to replace that one... It doesn't seem that it's currently possible to do what I'm asking.

**Comment by Thom1729** [comment]
Closing this because:

- JS Custom doesn't suggest disabling the core package.
- babel-sublime also doesn't suggest disabling the core package anymore.
