### ISSUE TITLE
False positives for goto_definition and goto_symbol_in_project

### ISSUE THREAD

**Issue by kylebebak** [Thom1729/Sublime-JS-Custom#44]
## Env
Running Sublime Text build 3176 on OSX, version v1.0.22 of this package.

## Steps to repro
I've included some screenshots to illustrate the problem.

First, using **Goto Symbol...**, one can see that neither "moreThanSix" or "required" are included in the list of symbols, because these are functions which are defined in another module.

<img width="1280" alt="screen shot 2018-08-23 at 1 03 10 pm" src="https://user-images.githubusercontent.com/1524088/44543517-5f2f9980-a6d5-11e8-9501-67ba52af85a8.png">

-----

However, hovering over "moreThanSix" or "required" and running **Goto Definition...** shows 3 results: the correct location of the definition of these functions, in the `validation.js` module, and **two false positives**, on lines 39 and 55 of the current module.

<img width="1280" alt="screen shot 2018-08-23 at 1 03 30 pm" src="https://user-images.githubusercontent.com/1524088/44543602-9dc55400-a6d5-11e8-91b6-113ade0f93b6.png">

The same false positives appear when running **Goto Symbol in Project...**. The names of these different commands, as far as Sublime Text is concerned, are as follows.

- command: goto_symbol_in_project
- command: goto_definition
- command: show_overlay {"overlay": "goto", "text": "@"}

## Observations
It's strange that symbols are being indexed that are not function or class definitions. **Goto Symbol...** command doesn't show these false positives, but **Goto Symbol in Project...** and **Goto Definition...** both do.

To be totally explicit, the `required` and `moreThanSix` functions are being indexed in places where they are merely being passed as arguments, not where they are defined.

I'm not sure if this is caused by the implementations of the `goto_symbol_in_project` and `goto_definition`, by the default JavaScript syntax for Sublime Text, or by JS Custom.

**Comment by Thom1729** [comment]
JS Custom shouldn't affect how symbols are resolved, so I expect that the issue is with the core syntax or symbol resolution system. Do you have a reproduceable example?

**Comment by kylebebak** [comment]
As I mentioned in #43 , I was probably not running the correct version of the core JavaScript syntax. This issue has disappeared for me, but another issue showed up which I describe in #43 . I'll close this.
