### ISSUE TITLE
Add support for emmet autocompletions inside CSS and update syntax

### ISSUE THREAD

**Issue by mohitsinghs** [Thom1729/Sublime-JS-Custom#46]
Hi @Thom1729 

I tried enabling emmet inside JSX and CSS and have made necessary changes to a [fork](https://github.com/mohitsinghs/JSCustom). These changes are against **next** branch.
I have also updated the syntax for styled components. 

I am using this setup locally.

So, I am curious if you are willing to review these changes.
In that case, I will open a pull request.

**Comment by Thom1729** [comment]
Can you give a brief summary of what the changes are? It didn't occur to me that JS Custom wouldn't be compatible with Emmet in the first place.

**Comment by mohitsinghs** [comment]
BTW, Thank you so much for such an awesome plugin.
I was using [sublime-language-babel](https://github.com/mohitsinghs/sublime-language-babel) with [sublime-typescript](https://github.com/mohitsinghs/sublime-typescript), but now I use a fork of yours.

**Comment by mohitsinghs** [comment]
This chnages can be safely ignored but here they are.

**Changes for enabling emmet autocompletions.**

1. [here](https://github.com/Thom1729/Sublime-JS-Custom/blob/7f6ef54a49dbaf5f2f3a2744de9d487f469f745c/extensions/styled_components.yaml#L26) we will clear the scope entirely.

from 
```yaml
clear_scopes: 1
```
to 
```yaml
clear_scopes: true
```

2. We will re-add the js scope [here](https://github.com/Thom1729/Sublime-JS-Custom/blob/7f6ef54a49dbaf5f2f3a2744de9d487f469f745c/extensions/styled_components.yaml#L39-L40).

from 
```yaml
- clear_scopes: 1
- meta_scope: meta.template.expression.js
```
to
```yaml
- clear_scopes: true
- meta_scope: >-
   soucre.js.react
   meta.template.expression.js
# or somehow we can re add the parent js scope in the case of customization
```

**Support Styled Components V4**

Not quite related but I added `createGlobalStyle` [here](https://github.com/Thom1729/Sublime-JS-Custom/blob/7f6ef54a49dbaf5f2f3a2744de9d487f469f745c/extensions/styled_components.yaml#L7)  for this.

**Proposed Syntax**
[here](https://github.com/mohitsinghs/sublime-language-babel/blob/master/Styled%20CSS.sublime-syntax) is the syntax I am using for Styled Components. I just removed a few interpolation related things.

**Comment by hudochenkov** [comment]
I started using Styled Components, and I'm happy I found JS Custom. Emmet doesn't work inside `styled` template literals. When I expand Emmet abbreviation by <kbd>Cmd</kbd>+<kbd>E</kbd> (type `dn`, press <kbd>Cmd</kbd>+<kbd>E</kbd>, get `display: none;`), it expands as HTML (I pretty sure it's Emmet's default). I didn't found a way to customize Emmet to work inside template literals to expand CSS abbreviations :( When I set file syntax to CSS — Emmet works.

It's not a problem in JS Custom or Emmet. I just want to make them work together. And based on @mohitsinghs comment it's possible to do.

@mohitsinghs what were your changes? Your repository is not available anymore :(

**Comment by mohitsinghs** [comment]
@hudochenkov Thanks for reminding me. I created #55 to solve this
I made that fork private a while back when I realized that my changes where too many and where personal choices but this specific change should be helpful for emmet addicts like me.
Let's hope this pr gets merged.
