### ISSUE TITLE
Installation fails on ST3 because of ruamel

### ISSUE THREAD

**Issue by abhishiv** [Thom1729/Sublime-JS-Custom#47]
Hey guys

Just tried to install JSCustom via package control, but it failed with a very weird error. As you can see it complains about `No module named 'ruamel'`, but I can see from the logs that it installed it. I also tried installing it manually via pip but same error.

Any idea what I might be doing wrong?

```
Package Control: The dependency 'ruamel-yaml' is not currently installed; installing...
Package Control: The dependency 'ruamel-yaml' has successfully been installed or updated
Package Control: The dependency 'yaml_macros_engine' is not currently installed; installing...
Package Control: The dependency 'yaml_macros_engine' has successfully been installed or updated
Package Control: The dependency 'sublime_lib' is not currently installed; installing...
Package Control: The dependency 'sublime_lib' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["SublimeHaskell", "Vintage"]
reloading plugin JSCustom.build_js_custom_syntaxes
reloading plugin JSCustom.jsx_close_tag_command
reloading plugin JSCustom.jsx_close_tag_listener
reloading settings Packages/JSCustom/sublime/JS Custom.sublime-settings
generating syntax summary
generating meta info summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1036, in run_
    return self.run()
  File "/Users/abhishiv/Library/Application Support/Sublime Text 3/Installed Packages/JSCustom.sublime-package/build_js_custom_syntaxes.py", line 70, in run
  File "/Users/abhishiv/Library/Application Support/Sublime Text 3/Packages/yaml_macros_engine/st3/yamlmacros/__init__.py", line 1, in <module>
    from .src.util import apply, raw_macro
  File "/Users/abhishiv/Library/Application Support/Sublime Text 3/Packages/yaml_macros_engine/st3/yamlmacros/src/util.py", line 3, in <module>
    import ruamel.yaml
ImportError: No module named 'ruamel'
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by Thom1729** [comment]
Does the problem go away if you restart Sublime?

**Comment by Thom1729** [comment]
This is odd.

1. Is there a directory called `ruamel-yaml` under `Packages`?
2. Type `import ruamel.yaml` into the Sublime console. Does it raise `ImportError`?

**Comment by Thom1729** [comment]
@abhishiv Have you run into this error again?

**Comment by jimmyhmiller** [comment]
@Thom1729 I'm having the exact same problem. Restarting sublime does not fix it. There is no directory called `ruamel-yaml` under `Packages` and `import ruamel.yaml` does cause an import error.

I am on MacOS 10.14.2. If there is anything I can do to help debug this, let me know.

**Comment by jimmyhmiller** [comment]
@Thom1729 I was getting the message `No module named 'ruamel'`. JSCustom would not be installed. It would still show up in package control to be installed and no folder was created. 

To give you the exact message I just tried to install again. And for some reason it worked. I don't think I had changed anything. Perhaps it was a network issue? I had tried install it several times before this to no avail.

**Comment by Thom1729** [comment]
Based on the evidence so far, it sounds like this was an issue with the installation process via Package Control rather than with JS Custom itself. Therefore, I'm going to close this issue. But if the problem recurs, and restarting/running the PC install command again doesn't fix it, then feel free to reopen or create a new issue.
