### ISSUE TITLE
Allow custom template tags by detecting comments

### ISSUE THREAD

**Issue by string-areeb** [Thom1729/Sublime-JS-Custom#49]
Like [this](https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates) Visual Studio Code Plugin, we could have people define different comments in front of their template literal which may resolve to a custom template tag, this will be specially beneficial for people not looking forward to adding a tag to their template literal(even a no-op one) for any reason.

So, for example
```js
const str = /* html */ `
<div class="col-xs">Hello</div>
`;

const style = /* css */ `
body {
  color: hotpink;
}
`;
```

Will detect and apply html and css grammars according to the user's prefernce

**Comment by Thom1729** [comment]
I imagine that this would be configured much like `custom_template_tags`:

```json
{
    "configurations": {
        "My Config": {
            "custom_template_comments": {
                "html": "scope:text.html.basic"
            }
        }
    }
}
```

Then, the extension would match `/* html */` followed by a backtick, with no intervening tokens or line breaks.

Does this sound like a satisfactory solution?

**Comment by string-areeb** [comment]
Yes, sounds good. Just allow whitespace to be between and within comment and literal, so that 

```
/*html*/   `<h1></h1>`
```

is matched as well

**Comment by luwes** [comment]
Was looking for the `html` syntax `"html": "scope:text.html.basic"`. Could be beneficial to add this to the readme example. My first idea was that it would be `scope:source.html` with the CSS example there...
