### ISSUE TITLE
entity.name.function.js scope still not applied to arrow functions inside class definitions

### ISSUE THREAD

**Issue by kylebebak** [Thom1729/Sublime-JS-Custom#52]
I installed ST build 3182, which includes the upstream fixes mentioned in #43 , and am running JS Custom v1.0.23.

```js
class A {
  method = () => {}
}
```

If I set the syntax to plain **JavaScript**, `method` is indexed, which means the upstream fix works.

However, if I set the syntax to **JS Custom - Default** or **JS Custom - React**, `method` is not indexed.

I tried removing the **User/JS Custom** folder and rebuilding the syntaxes to no avail. I also tried uninstalling JS Custom and reinstalling it.

I am using the default `JS Custom.sublime-settings` that ships with the plugin.

Maybe I'm doing something stupid, but I've looked at the README and I can't figure out what!

**Comment by Thom1729** [comment]
It looks like some of those changes didn't go out in the update. I'll sort this out sometime today.

**Comment by kylebebak** [comment]
Ahh right on, thanks!

**Comment by kylebebak** [comment]
Thanks, it's working! Gonna close this
