### ISSUE TITLE
Overriding styling of template tags?

### ISSUE THREAD

**Issue by Twipped** [Thom1729/Sublime-JS-Custom#60]
I'd like to alter the styling of template strings so that the background color differs from other code (otherwise the new scope kinda blends in with the JS scope and it isn't obvious at first glance that it's a template).

Is there a way to accomplish this via configuration, or would I have to edit the package?

**Comment by Twipped** [comment]
I dug into the source of the package and discovered that, no, this isn't available, but I managed to get the effect I wanted by adding `string.template.js` to my theme's Embedded Source scope list. This wasn't a full success, however, as it only changed the background of the template tag and backticks. 

Adding `- meta_content_scope: source` right after the `meta_scope: string.template.js` definition for each tagged template solved this problem, but so did removing the `clear_scopes` line.

**Comment by Thom1729** [comment]
The core JavaScript syntax should probably be using `meta.string.template string.template` or the like for template strings. If it did, then JS Custom would follow suit, and you could style `meta.string.template`. If you open an issue in the [core Packages repo](https://github.com/sublimehq/Packages/issues), then I'll try to get to it soon.
