### ISSUE TITLE
Error constructor is not considered a built-in

### ISSUE THREAD

**Issue by nwoltman** [Thom1729/Sublime-JS-Custom#61]
With this code

```js
new Error()
```

the `Error` constructor has the scope

```
support.class.error.js
```

but it seems like it should be

```
support.class.builtin.error.js
```

Without the `support.class.builtin` part, the `Error` constructor doesn't get highlighted like the other built-in constructors (`Array`, `Date`, etc.).

**Comment by Thom1729** [comment]
This is consistent with the core JavaScript syntax. It seems sensible to change this; if you open an issue on the [core Packages tracker](https://github.com/sublimehq/Packages), I can probably get to it soon.
