### ISSUE TITLE
Does not auto build syntax definitions on installation from package control

### ISSUE THREAD

**Issue by nhooyr** [Thom1729/Sublime-JS-Custom#62]
I had to manually rebuild for the syntaxes to show up.

**Comment by nhooyr** [comment]
Styled components also don't seem to be syntax highlighted or have completion available unlike the babel repo.

**Comment by Thom1729** [comment]
> I had to manually rebuild for the syntaxes to show up.

Were there any errors in the console?

> Styled components also don't seem to be syntax highlighted or have completion available unlike the babel repo.

Did you set `styled_components: true` in your configuration? It's not enabled in the default configuration.

**Comment by nhooyr** [comment]
> Did you set styled_components: true in your configuration? It's not enabled in the default configuration.

My bad, only skimmed the docs.

> Were there any errors in the console?

Did not check at the time. Just retried and they showed up. I'm not sure what's going on.

Something I did notice is uninstalling this plugin causes sublime text to hang for me. I have to force quit it. Not sure what's going on.

Here's how it looked:

<img width="1274" alt="Screen Shot 2019-05-11 at 11 11 16 PM" src="https://user-images.githubusercontent.com/10180857/57577318-16c23280-7442-11e9-80bb-268bcff947ef.png">

I uninstalled via package control.

**Comment by Thom1729** [comment]
Hmm. That looks like a Package Control internal error (though it could be indirectly caused by JS Custom). That might be hard to troubleshoot.

**Comment by nhooyr** [comment]
Got the rebuild issue to happen again:

<img width="1274" alt="Screen Shot 2019-05-11 at 11 19 11 PM" src="https://user-images.githubusercontent.com/10180857/57577378-386fe980-7443-11e9-9842-d2dcbb3b1c85.png">

**Comment by nhooyr** [comment]
As you can see, its installed but the syntax themes aren't there.

**Comment by nhooyr** [comment]
Once I hit rebuild, they show up.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
