### ISSUE TITLE
Missing scopes when importing/exporting Flow types

### ISSUE THREAD

**Issue by nwoltman** [Thom1729/Sublime-JS-Custom#69]
Flow supports directly importing/exporting types, however, the correct scope isn't being added to the `type` keyword in imports/exports and directly exported types are missing Flow scopes altogether.

```js
/**
 * @flow
 */

// `type` is missing "storage.type.js" scope
import {type UserID} from 'AppTypes';

type User = {|
  id: UserID,
  name: string,
|};

// `type` is missing "storage.type.js" scope
export type {User};

// Missing all Flow-related scopes
export type Friend = {|
  id: UserID,
  name: string,
|};
```

Result:
![Flow-sublime](https://user-images.githubusercontent.com/5128013/61154513-4fbb6980-a4bc-11e9-985c-6852264b090b.png)

**Comment by nwoltman** [comment]
Thanks for the quick fix @Thom1729! 😄

**Comment by Thom1729** [comment]
Thanks for the report!
