### ISSUE TITLE
"get"/"set" as object keys breaks highlighting

### ISSUE THREAD

**Issue by nwoltman** [Thom1729/Sublime-JS-Custom#70]
When the strings `get` and `set` are used as object keys, the wrong scopes are applied because the syntax thinks they are defining getter/setter keys (but they're just plain string keys).

```js
Object.defineProperties(Response.prototype, {
  append: Object.getOwnPropertyDescriptor(Response.prototype, 'appendHeader'),
  get: Object.getOwnPropertyDescriptor(Response.prototype, 'getHeader'),
  has: Object.getOwnPropertyDescriptor(Response.prototype, 'hasHeader'),
  remove: Object.getOwnPropertyDescriptor(Response.prototype, 'removeHeader'),
  set: Object.getOwnPropertyDescriptor(Response.prototype, 'setHeader'),
})
```

Result:
![get-set-sublime](https://user-images.githubusercontent.com/5128013/61154917-7f1ea600-a4bd-11e9-9bec-5be5c09d20f3.png)

**Comment by Thom1729** [comment]
The bug is actually in the core syntax, so I've written a PR there.
