### ISSUE TITLE
Better syntax highlighting for destructured variables

### ISSUE THREAD

**Issue by trongthanh** [Thom1729/Sublime-JS-Custom#80]
From what I observe in Firefox and Chrome's consoles, I notice that they provide good visibility on which identifiers are the variables, which are just object's key names in a destructuring assignment.

For example, with below code:
```js
const obj = {
	prop: {
		deeperProp: 123,
	}
};

const {prop, prop: {deeperProp: renamed}, ...rest} = obj;
```

Firefox console display as:
![image](https://user-images.githubusercontent.com/234226/66902590-1cdcc080-f02b-11e9-9552-e537a36e125b.png)

in which, `prop`, `renamed` and `rest` are clearly variables. 

IMO, destructuring assignment with renamed variable and nested selectors make it confusing to grope which name is the final variables. With this custom syntax, I think it will really help developers especially newbies to this powerful but not easy feature of the language.

Can you help suggest a config that I can achieve such effect?

**Comment by Thom1729** [comment]
JS Custom actually does the necessary work for this (actually, the core JavaScript syntax does). However, the default color schemes do not. Example:

```js
const { key: variable } = obj;
```

`key` is scoped `meta.object-literal.key` and `variable` is scoped `meta.binding.name variable.other.readwrite`.

I'm using a modified version of the built-in Mariana color scheme:

```json
{
    "variables": <snip>,
    "globals":  <snip>,
    "rules": [
        {
            "name": "JavaScript unquoted object literal key",
            "scope": "meta.object-literal.key, meta.object-literal.key string - punctuation, meta.mapping.key string - punctuation, meta.structure.dictionary.key string - punctuation",
            "foreground": "var(blue5)"
        },
    ]
}
```

This causes keys to be highlighted in object literals and destructuring assignments:

<img width="228" alt="Screen Shot 2019-10-16 at 09 57 41" src="https://user-images.githubusercontent.com/16958499/66926140-788f5580-effb-11e9-986e-3c62eb676dbe.png">

I find this change to be extremely useful. I think I'll bring up the idea of adding it to the default color schemes, though there's a high bar for that.

Does this change solve your problem?

**Comment by trongthanh** [comment]
@Thom1729  Thanks for your great explanation. I tried your patch to Mariana scheme and found a small issue. Here's how it look with some nested destructuring:

![image](https://user-images.githubusercontent.com/234226/66977922-09386500-f0d2-11e9-9d19-e49bf3fb06a7.png)

All destructuring bindings without rename have object literal's key color (in this case the first `prop`) which doesn't help distinguish from variables and just key names.

I have tweaked the scope selector a bit at this part:
```
meta.object-literal.key - meta.binding.name
```
And now I can see what come out of destructuring assignment as variables:

![image](https://user-images.githubusercontent.com/234226/66978227-44876380-f0d3-11e9-80f8-e9b4420b45e4.png)

So I guess you can close this ticket now.
