### ISSUE TITLE
Add the location of syntaxes to the Usage section of README

### ISSUE THREAD

**Issue by Shelagh-Lewins** [Thom1729/Sublime-JS-Custom#81]
I spent some time trying to work out how to enable JS Custom, because I couldn't see it in the syntaxes list.

The answer is mentioned right at the bottom of the README under Frequently Asked Questions, but I think it'd be really helpful to put this information at the top under "Usage" because that's where users look for basic, essential instructions.

Perhaps you could add something like "To select JS Custom syntax for a file, open the syntax selection menu at the bottom right of the Sublime Text screen and choose User > JS Custom React or User > JS Custom Default."

It would also be really useful information to add to the package control message that you see on installing the package.

Thanks for the great plugin!

**Comment by Thom1729** [comment]
@Shelagh-Lewins How does PR #82 look?

**Comment by little-brain** [comment]
Thank you, looks good to me!
