### ISSUE TITLE
Update for next Sublime version

### ISSUE THREAD

**Issue by Thom1729** [Thom1729/Sublime-JS-Custom#91]
Sublime dev builds offer new highlighting features, and new versions of the core JavaScript syntax use those features (and provide better highlighting as a result). At some point, JS Custom will update to use the new core syntax. This will be a breaking change; it will only be compatible with future Sublime versions.

The next version should:

- Use the new core JavaScript syntax (probably requiring changes to some extensions).
- Take advantage of new syntax features, especially branching.
- Use the new plugin runtime and take advantage of its features.

The current major version:

- Will still be available and will continue to work for older Sublime versions.
- Will not be kept up to date with the core JavaScript syntax.
- Probably will not receive new features.

**Comment by Thom1729** [comment]
For anyone watching this, my current plan is to release v2.4 for current versions of Sublime with beta-quality TypeScript support (see #51). There probably won't be a v2.5, and v3 will require a newer version of Sublime. This plan may change.

**Comment by Thom1729** [comment]
v2.4 has been out for some time with experimental TypeScript support. It's based on the most recent ST3-compatible core syntax and will most likely not receive any updates except for critical bug fixes.

v3.0 is in alpha, but it's probably ready for beta. It features the latest core improvements, taking full advantage of the new features of ST4. TypeScript support is greatly improved over v2.4 (it should be identical to the new core TypeScript syntax). Most likely, only v3.0 and further will get new features.

If you're on the ST4 beta, you can get the latest JS Custom 3.0 alpha by adding `"install_prereleases": ["JSCustom"]` to your Package Control config.

**Comment by isubasti** [comment]
I can't seem to find `JSCustom` on ST4 beta's pacakages

**Comment by Thom1729** [comment]
@isubasti I suspect the problem was actually that I set up the new ST4 tags incorrectly in the Package Control channel. I've just officially released v3.0.0 — please let me know if you can install it! (It may take a couple of hours for Package Control to pick it up.)

**Comment by Thom1729** [comment]
How can I see that the Needs Review flag is set?

**Comment by michaelblyons** [comment]
On the [PC page](https://packagecontrol.io/packages/JSCustom), you'll see "NEEDS REVIEW" with a little yellow ⓘ, next to "by Thom1729"

**Comment by wbond** [comment]
I cleared the review flag earlier today.

**Comment by Thom1729** [comment]
Thanks for the fix!

**Comment by Thom1729** [comment]
@isubasti Is it working for you now?

**Comment by isubasti** [comment]
@Thom1729 It is indeed working now

**Comment by Thom1729** [comment]
Since the tags for v3 got messed up, and we ended up with an ST3-compatible v3, I just bumped the ST4 stuff to v4. It's out and stable, so I'm closing.
